project:
  type: website
  output-dir: docs
website:
  title: "CURE ID"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Intro"
        contents:
          - index.qmd
          - intro.qmd
      - section: "Process"
        contents:
          - sop.qmd
          - interpret.qmd
      - section: "Support"
        contents:
          - support.qmd
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
